stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint --verbose=0 src/units.h
    - cpplint --verbose=0 src/constants.h
    - cpplint --verbose=0 src/convacc.h
    - cpplint --verbose=0 src/convang.h
    - cpplint --verbose=0 src/convangacc.h
    - cpplint --verbose=0 src/convangvel.h
    - cpplint --verbose=0 src/convdensity.h
    - cpplint --verbose=0 src/convforce.h
    - cpplint --verbose=0 src/convlength.h
    - cpplint --verbose=0 src/convmass.h
    - cpplint --verbose=0 src/convpres.h
    - cpplint --verbose=0 src/convtemp.h
    - cpplint --verbose=0 src/convvel.h

Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/units_test
  
Test Units:
  stage: test
  tags:
    - bfs
  script:
    - ./build/units_test
