stages:
  - lint
  - build
  - test

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint.py --verbose=0 include/units/units.h
    - cpplint.py --verbose=0 include/units/constants.h
    - cpplint.py --verbose=0 include/units/convacc.h
    - cpplint.py --verbose=0 include/units/convang.h
    - cpplint.py --verbose=0 include/units/convangacc.h
    - cpplint.py --verbose=0 include/units/convangvel.h
    - cpplint.py --verbose=0 include/units/convdensity.h
    - cpplint.py --verbose=0 include/units/convforce.h
    - cpplint.py --verbose=0 include/units/convlength.h
    - cpplint.py --verbose=0 include/units/convmass.h
    - cpplint.py --verbose=0 include/units/convpres.h
    - cpplint.py --verbose=0 include/units/convtemp.h
    - cpplint.py --verbose=0 include/units/convvel.h

Compile:
  stage: build
  tags:
    - bfs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/units_test
  
Test Units:
  stage: test
  tags:
    - bfs
  script:
    - ./build/units_test
